# Generated by Django 3.0.8 on 2020-08-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20200810_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionslist',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ManyToManyField(blank=True, to='auctions.AuctionsList')),
            ],
        ),
    ]
