# Generated by Django 2.2.12 on 2020-08-14 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200810_1859'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
